-- MySQL Script generated by MySQL Workbench
-- Mon Apr  9 14:04:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BD-LES
-- -----------------------------------------------------
-- Base de Datos - LES
-- Fernando M.
-- 
DROP SCHEMA IF EXISTS `BD-LES` ;

-- -----------------------------------------------------
-- Schema BD-LES
--
-- Base de Datos - LES
-- Fernando M.
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BD-LES` DEFAULT CHARACTER SET utf8 ;
USE `BD-LES` ;

-- -----------------------------------------------------
-- Table `BD-LES`.`Projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Projeto` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Projeto` (
  `idProjeto` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataFim` DATETIME NOT NULL,
  `AutorizacaoDGVA` VARCHAR(45) NULL,
  `RefORBEA` INT NULL,
  `SubmisInsEurop` TINYINT(1) NULL,
  `nroAnimaisAutoriz` INT NULL,
  PRIMARY KEY (`idProjeto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Circuito_Tanque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Circuito_Tanque` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Circuito_Tanque` (
  `idCircuito` INT NOT NULL AUTO_INCREMENT,
  `Projeto_idProjeto` INT NOT NULL,
  `codigoCircuito` VARCHAR(15) NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataFinal` DATETIME NOT NULL,
  PRIMARY KEY (`idCircuito`),
  INDEX `fk_Circuito_Tanque_Projeto1_idx` (`Projeto_idProjeto` ASC),
  CONSTRAINT `fk_Circuito_Tanque_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `BD-LES`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Motivo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Motivo` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Motivo` (
  `idMotivo` INT NOT NULL AUTO_INCREMENT,
  `tipoMotivo` VARCHAR(45) NOT NULL,
  `nomeMotivo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMotivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Grupo` (
  `idGrupo` INT NOT NULL AUTO_INCREMENT,
  `NomeGrupo` VARCHAR(45) NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Familia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Familia` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Familia` (
  `idFamilia` INT NOT NULL AUTO_INCREMENT,
  `Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idFamilia`, `Grupo_idGrupo`),
  INDEX `fk_Familia_Grupo1_idx` (`Grupo_idGrupo` ASC),
  CONSTRAINT `fk_Familia_Grupo1`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `BD-LES`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Especie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Especie` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Especie` (
  `idEspecie` INT NOT NULL AUTO_INCREMENT,
  `NomeCient` VARCHAR(45) NULL,
  `NomeVulgar` VARCHAR(45) NULL,
  `Familia_idFamilia` INT NOT NULL,
  `Familia_Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idEspecie`, `Familia_idFamilia`, `Familia_Grupo_idGrupo`),
  INDEX `fk_Especie_Familia1_idx` (`Familia_idFamilia` ASC, `Familia_Grupo_idGrupo` ASC),
  CONSTRAINT `fk_Especie_Familia1`
    FOREIGN KEY (`Familia_idFamilia` , `Familia_Grupo_idGrupo`)
    REFERENCES `BD-LES`.`Familia` (`idFamilia` , `Grupo_idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`FornecedorColector`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`FornecedorColector` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`FornecedorColector` (
  `idFornColect` INT NOT NULL AUTO_INCREMENT,
  `Tipo` CHAR(1) NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `NIF` INT(10) NULL,
  `nroLicenca` INT NULL,
  `Morada` VARCHAR(45) NULL,
  `telefone` VARCHAR(10) NULL,
  PRIMARY KEY (`idFornColect`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`T_Origem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`T_Origem` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`T_Origem` (
  `idT_Origem` INT NOT NULL AUTO_INCREMENT,
  `Descrição` VARCHAR(45) NULL,
  PRIMARY KEY (`idT_Origem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Distrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Distrito` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Distrito` (
  `id` INT NOT NULL,
  `nomeDistrito` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Conselho`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Conselho` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Conselho` (
  `id` INT NOT NULL,
  `nomeConselho` VARCHAR(45) NOT NULL,
  `Distrito_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Distrito_id`),
  INDEX `fk_Conselho_Distrito1_idx` (`Distrito_id` ASC),
  CONSTRAINT `fk_Conselho_Distrito1`
    FOREIGN KEY (`Distrito_id`)
    REFERENCES `BD-LES`.`Distrito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`LocalCaptura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`LocalCaptura` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`LocalCaptura` (
  `idLocalCaptura` INT NOT NULL,
  `Localidade` VARCHAR(45) NULL,
  `Latitude` FLOAT(10,6) NULL,
  `Longitude` FLOAT(10,6) NULL,
  `Conselho_id` INT NOT NULL,
  `Conselho_Distrito_id` INT NOT NULL,
  PRIMARY KEY (`idLocalCaptura`, `Conselho_id`, `Conselho_Distrito_id`),
  INDEX `fk_LocalCaptura_Conselho1_idx` (`Conselho_id` ASC, `Conselho_Distrito_id` ASC),
  CONSTRAINT `fk_LocalCaptura_Conselho1`
    FOREIGN KEY (`Conselho_id` , `Conselho_Distrito_id`)
    REFERENCES `BD-LES`.`Conselho` (`id` , `Distrito_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`TipoEstatutoGenetico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`TipoEstatutoGenetico` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`TipoEstatutoGenetico` (
  `idTipoEstatutoGenetico` INT NOT NULL,
  `TipoEstatutoGeneticocol` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipoEstatutoGenetico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Funcionario` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Funcionario` (
  `idFuncionario` INT NOT NULL AUTO_INCREMENT,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `nomeUtilizador` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idFuncionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Reg_Novos_Animais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Reg_Novos_Animais` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Reg_Novos_Animais` (
  `idRegAnimal` INT NOT NULL AUTO_INCREMENT,
  `nroExemplares` INT NOT NULL,
  `nroMachos` INT NULL,
  `nroFemeas` INT NULL,
  `Imaturos` INT NULL,
  `Juvenis` INT NULL,
  `Larvas` INT NULL,
  `Ovos` INT NULL,
  `dataNasc` DATETIME NULL,
  `idade` INT NULL,
  `pesoMedio` FLOAT NULL,
  `compMedio` FLOAT NULL,
  `DuracaoViagem` TIME NULL,
  `tempPartida` INT NULL,
  `tempChegada` INT NULL,
  `nroContentores` INT NULL,
  `tipoContentor` VARCHAR(45) NULL,
  `volContentor` FLOAT NULL,
  `volAgua` FLOAT NULL,
  `nroCaixasIsoter` INT NULL,
  `nroMortosCheg` INT NULL,
  `satO2Transp` FLOAT NULL,
  `anestesico` FLOAT NULL,
  `Gelo` TINYINT(1) NULL,
  `Adicao_O2` TINYINT(1) NULL,
  `Arejamento` TINYINT(1) NULL,
  `refrigeracao` TINYINT(1) NULL,
  `sedação` TINYINT(1) NULL,
  `respTransporte` VARCHAR(45) NULL,
  `Especie_idEspecie` INT NOT NULL,
  `Fornecedor_idFornColect` INT NOT NULL,
  `T_Origem_idT_Origem` INT NOT NULL,
  `LocalCaptura_idLocalCaptura` INT NULL,
  `TipoEstatutoGenetico_idTipoEstatutoGenetico` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idRegAnimal`),
  CONSTRAINT `fk_Reg_Novos_Animais_Especie1`
    FOREIGN KEY (`Especie_idEspecie`)
    REFERENCES `BD-LES`.`Especie` (`idEspecie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Novos_Animais_Fornecedor1`
    FOREIGN KEY (`Fornecedor_idFornColect`)
    REFERENCES `BD-LES`.`FornecedorColector` (`idFornColect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Novos_Animais_T_Origem1`
    FOREIGN KEY (`T_Origem_idT_Origem`)
    REFERENCES `BD-LES`.`T_Origem` (`idT_Origem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Novos_Animais_LocalCaptura1`
    FOREIGN KEY (`LocalCaptura_idLocalCaptura`)
    REFERENCES `BD-LES`.`LocalCaptura` (`idLocalCaptura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Novos_Animais_TipoEstatutoGenetico1`
    FOREIGN KEY (`TipoEstatutoGenetico_idTipoEstatutoGenetico`)
    REFERENCES `BD-LES`.`TipoEstatutoGenetico` (`idTipoEstatutoGenetico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Novos_Animais_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `BD-LES`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Lote` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Lote` (
  `idLote` INT NOT NULL AUTO_INCREMENT,
  `codigoLote` VARCHAR(10) NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataFim` DATETIME NULL,
  `Observacoes` VARCHAR(45) NULL,
  `Reg_Novos_Animais_idRegAnimal` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idLote`),
  INDEX `fk_Lote_Reg_Novos_Animais1_idx` (`Reg_Novos_Animais_idRegAnimal` ASC),
  INDEX `fk_Lote_Funcionario1_idx` (`Funcionario_idFuncionario` ASC),
  CONSTRAINT `fk_Lote_Reg_Novos_Animais1`
    FOREIGN KEY (`Reg_Novos_Animais_idRegAnimal`)
    REFERENCES `BD-LES`.`Reg_Novos_Animais` (`idRegAnimal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lote_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `BD-LES`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Tanque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Tanque` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Tanque` (
  `idTanque` INT NOT NULL AUTO_INCREMENT,
  `nroAnimais` INT NOT NULL,
  `sala` VARCHAR(15) NOT NULL,
  `observacoes` VARCHAR(45) NULL,
  `Lote_idLote` INT NOT NULL,
  `Circuito_Tanque_idCircuito` INT NOT NULL,
  PRIMARY KEY (`idTanque`),
  INDEX `fk_Tanque_Lote1_idx` (`Lote_idLote` ASC),
  INDEX `fk_Tanque_Circuito_Tanque1_idx` (`Circuito_Tanque_idCircuito` ASC),
  CONSTRAINT `fk_Tanque_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `BD-LES`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tanque_Circuito_Tanque1`
    FOREIGN KEY (`Circuito_Tanque_idCircuito`)
    REFERENCES `BD-LES`.`Circuito_Tanque` (`idCircuito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Reg_Remocoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Reg_Remocoes` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Reg_Remocoes` (
  `idRegRemo` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `nroRemoções` INT NULL,
  `Motivo_idMotivo` INT NOT NULL,
  `causaMorte` CHAR(1) NULL,
  `Tanque_idTanque` INT NOT NULL,
  PRIMARY KEY (`idRegRemo`),
  CONSTRAINT `fk_Reg_Remocoes_Motivo1`
    FOREIGN KEY (`Motivo_idMotivo`)
    REFERENCES `BD-LES`.`Motivo` (`idMotivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Remocoes_Tanque1`
    FOREIGN KEY (`Tanque_idTanque`)
    REFERENCES `BD-LES`.`Tanque` (`idTanque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Reg_Amostragens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Reg_Amostragens` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Reg_Amostragens` (
  `idRegAmo` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `pesoMedio` FLOAT NOT NULL,
  `nroIndividuos` INT NOT NULL,
  `pesoTotal` FLOAT NOT NULL,
  `Tanque_idTanque` INT NOT NULL,
  PRIMARY KEY (`idRegAmo`),
  CONSTRAINT `fk_Reg_Amostragens_Tanque1`
    FOREIGN KEY (`Tanque_idTanque`)
    REFERENCES `BD-LES`.`Tanque` (`idTanque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Reg_Cond_Amb`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Reg_Cond_Amb` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Reg_Cond_Amb` (
  `idRegCondAmb` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `temperatura` FLOAT NULL,
  `volAgua` FLOAT NULL,
  `salinidadeAgua` FLOAT NULL,
  `nivelO2` FLOAT NULL,
  `Circuito_Tanque_idCircuito` INT NOT NULL,
  PRIMARY KEY (`idRegCondAmb`),
  CONSTRAINT `fk_Reg_Cond_Amb_Circuito_Tanque1`
    FOREIGN KEY (`Circuito_Tanque_idCircuito`)
    REFERENCES `BD-LES`.`Circuito_Tanque` (`idCircuito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Finalidade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Finalidade` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Finalidade` (
  `idFinalidade` INT NOT NULL AUTO_INCREMENT,
  `T_Finalidade` VARCHAR(45) NULL,
  PRIMARY KEY (`idFinalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`agente_Trat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`agente_Trat` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`agente_Trat` (
  `idAgenTra` INT NOT NULL AUTO_INCREMENT,
  `nomeAgenTra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAgenTra`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Reg_Tratamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Reg_Tratamento` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Reg_Tratamento` (
  `idRegTra` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NOT NULL,
  `Tempo` INT NOT NULL,
  `Concentracao` FLOAT NOT NULL,
  `Finalidade_idFinalidade` INT NOT NULL,
  `agente_Trat_idAgenTra` INT NOT NULL,
  `concAgenTra` INT NULL,
  `Tanque_idTanque` INT NOT NULL,
  PRIMARY KEY (`idRegTra`),
  CONSTRAINT `fk_Reg_Tratamento_Finalidade1`
    FOREIGN KEY (`Finalidade_idFinalidade`)
    REFERENCES `BD-LES`.`Finalidade` (`idFinalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Tratamento_agente_Trat1`
    FOREIGN KEY (`agente_Trat_idAgenTra`)
    REFERENCES `BD-LES`.`agente_Trat` (`idAgenTra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Tratamento_Tanque1`
    FOREIGN KEY (`Tanque_idTanque`)
    REFERENCES `BD-LES`.`Tanque` (`idTanque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Tipo_Manuntecao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Tipo_Manuntecao` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Tipo_Manuntecao` (
  `idT_Manutencao` INT NOT NULL AUTO_INCREMENT,
  `T_Manutencao` VARCHAR(45) NULL,
  PRIMARY KEY (`idT_Manutencao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Reg_Manutencao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Reg_Manutencao` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Reg_Manutencao` (
  `idRegMan` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `Tipo_Manuntecao_idT_Manutencao` INT NOT NULL,
  `Tanque_idTanque` INT NOT NULL,
  PRIMARY KEY (`idRegMan`),
  CONSTRAINT `fk_Reg_Manutencao_Tipo_Manuntecao1`
    FOREIGN KEY (`Tipo_Manuntecao_idT_Manutencao`)
    REFERENCES `BD-LES`.`Tipo_Manuntecao` (`idT_Manutencao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Manutencao_Tanque1`
    FOREIGN KEY (`Tanque_idTanque`)
    REFERENCES `BD-LES`.`Tanque` (`idTanque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Plano_Alimentar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Plano_Alimentar` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Plano_Alimentar` (
  `idPlanAlim` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `MarcaAlim` VARCHAR(45) NULL,
  `Tipo` INT NOT NULL,
  `Temperatura` FLOAT NOT NULL,
  `Racao` FLOAT NULL,
  `RacaoDia` FLOAT NOT NULL,
  PRIMARY KEY (`idPlanAlim`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Reg_Alimentar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Reg_Alimentar` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Reg_Alimentar` (
  `idRegAlim` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `Peso` FLOAT NOT NULL,
  `Sobras` FLOAT NULL,
  `Plano_Alimentar_idPlanAlim` INT NOT NULL,
  `Tanque_idTanque` INT NOT NULL,
  PRIMARY KEY (`idRegAlim`),
  CONSTRAINT `fk_Reg_Alimentar_Plano_Alimentar1`
    FOREIGN KEY (`Plano_Alimentar_idPlanAlim`)
    REFERENCES `BD-LES`.`Plano_Alimentar` (`idPlanAlim`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reg_Alimentar_Tanque1`
    FOREIGN KEY (`Tanque_idTanque`)
    REFERENCES `BD-LES`.`Tanque` (`idTanque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Origem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Origem` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Origem` (
  `idOrigem` INT NOT NULL,
  `TipoOrigem` INT NULL,
  PRIMARY KEY (`idOrigem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Lote_Sub_Lote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Lote_Sub_Lote` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Lote_Sub_Lote` (
  `Lote_idLote_prev` INT NOT NULL,
  `Lote_idLote_atual` INT NOT NULL,
  `codigoSubLote` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Lote_idLote_prev`, `Lote_idLote_atual`),
  INDEX `fk_Sub_Lote_Lote1_idx` (`Lote_idLote_prev` ASC),
  INDEX `fk_Sub_Lote_Lote2_idx` (`Lote_idLote_atual` ASC),
  CONSTRAINT `fk_Sub_Lote_Lote1`
    FOREIGN KEY (`Lote_idLote_prev`)
    REFERENCES `BD-LES`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sub_Lote_Lote2`
    FOREIGN KEY (`Lote_idLote_atual`)
    REFERENCES `BD-LES`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`elementoEquipa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`elementoEquipa` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`elementoEquipa` (
  `idElementoEquipa` INT NOT NULL AUTO_INCREMENT,
  `função` VARCHAR(40) NOT NULL,
  `Projeto_idProjeto` INT NOT NULL,
  `Funcionario_idFuncionario` INT NOT NULL,
  PRIMARY KEY (`idElementoEquipa`),
  CONSTRAINT `fk_equipaProjeto_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `BD-LES`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipaProjeto_Funcionario1`
    FOREIGN KEY (`Funcionario_idFuncionario`)
    REFERENCES `BD-LES`.`Funcionario` (`idFuncionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BD-LES`.`Ensaio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `BD-LES`.`Ensaio` ;

CREATE TABLE IF NOT EXISTS `BD-LES`.`Ensaio` (
  `idEnsaio` INT NOT NULL AUTO_INCREMENT,
  `dataInicio` DATETIME NOT NULL,
  `dataFim` DATETIME NOT NULL,
  `descTratamento` VARCHAR(45) NOT NULL,
  `grauSeveridade` INT NOT NULL,
  `Projeto_idProjeto` INT NOT NULL,
  `Lote_idLote` INT NOT NULL,
  `membroEquipa_idEquipa` INT NOT NULL,
  PRIMARY KEY (`idEnsaio`),
  CONSTRAINT `fk_Ensaio_Projeto1`
    FOREIGN KEY (`Projeto_idProjeto`)
    REFERENCES `BD-LES`.`Projeto` (`idProjeto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ensaio_Lote1`
    FOREIGN KEY (`Lote_idLote`)
    REFERENCES `BD-LES`.`Lote` (`idLote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
